# Site settings
title: 长颈鹿时间
email: liangzhewei@gmail.com
timezone: Asia/Shanghai
description: > # this means to ignore newlines until "baseurl:"
    成都优鹿科技 用科技助力实体商家的生意，提高一站式解决方案，包括：商业Wi-Fi、老顾客甄别、应用统计、网络覆盖等信息服务，让商家彻底抛开IT方面的负担，专注于提升用户体验，最大限度提升自身服务质量，在市场上占领先机.
keywords: >
    Wi-Fi, mobile, 商业Wi-Fi，智能路由器，商业路由器，甄别老顾客，回头客，信息服务
baseurl: "/giraffa_time" # the subpath of your site, e.g. /blog/
url: "http://xavierliang.github.com" # the base hostname & protocol for your site
github_username:  xavierliang

# Build settings
markdown: kramdown
