title: 长颈鹿时间
description: >
    成都优鹿科技 用科技助力商家的生意，提供一站式解决方案，包括：商业Wi-Fi，老顾客甄别、应用统计、网络覆盖等信息服务，让商家彻底抛开IT方面的负担，专注于提升用户体验，最大限度提升自身服务质量，在市场上占领先机。
keywords:
    Wi-Fi, mobile, 商业Wi-Fi，智能路由器，甄别老顾客，回头客，信息服务

baseurl: "/giraffa_time"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 主页
   url: /index.html
 - title: 关于
   url: /about.html
 - title: 联系我们
   url: /contact.html

social:
   github: xavierliang
   email: liangzhewei@gmail.com

